country_abbreviations = {
    "Algeria" : "DZ",
    "Argentina" : "AR",
    "Australia" : "AU",
    "Austria" : "AT",
    "Azerbaijan" : "AZ",
    "Bangladesh" : "BD",
    "Belarus" : "BY",
    "Belgium" : "BE",
    "Brazil" : "BR",
    "Bulgaria" : "BG",
    "Cambodia" : "KH",
    "Canada" : "CA",
    "Chile" : "CL",
    "China" : "CN",
    "Columbia" : "CO",
    "Croatia" : "HR",
    "Cuba" : "CU",
    "Czechia" : "CZ",
    "Denmark" : "DK",
    "Dominican Republic" : "DO",
    "Ecuador" : "EC",
    "Egypt" : "EG",
    "Estonia" : "EE",
    "Ethiopia" : "ET",
    "European Union" : "EU",
    "Finland" : "FI",
    "France" : "FR",
    "Germany" : "DE",
    "Greece" : "GR",
    "Guatemala" : "GT",
    "Honduras" : "HN",
    "Hong Kong" : "HK",
    "Hungary" : "HU",
    "India" : "IN",
    "Indonesia" : "ID",
    "Iran" : "IR",
    "Iraq" : "IQ",
    "Ireland" : "IE",
    "Israel" : "IL",
    "Italy" : "IT",
    "Japan" : "JP",
    "Kazakhstan" : "KZ",
    "Kenya" : "KE",
    "Kuwait" : "KW",
    "Latvia" : "LV",
    "Lebanon" : "LB",
    "Lithuania" : "LT",
    "Luxembourg" : "LU",
    "Malaysia" : "MY",
    "Mexico" : "MX",
    "Mongolia" : "MN",
    "Morocco" : "MA",
    "Netherlands" : "NL",
    "New Zealand" : "NZ",
    "Nigeria" : "NG",
    "North Macedonia" : "MK",
    "Norway" : "NO",
    "Oman" : "OM",
    "Pakistan" : "PK",
    "Panama" : "PA",
    "Paraguey" : "PY",
    "Peru" : "PE",
    "Philippines" : "PH",
    "Poland" : "PL",
    "Portugal" : "PT",
    "Qatar" : "QA",
    "Romania" : "RO",
    "Russian Federation" : "RU",
    "Saudi Arabia" : "SA",
    "Serbia" : "RS",
    "Singapore" : "SG",
    "Slovakia" : "SK",
    "Slovenia" : "SI",
    "South Africa" : "ZA",
    "South Korea" : "KR",
    "Spain" : "ES",
    "Sweden" : "SE",
    "Switzerland" : "CH",
    "Taiwan" : "TW",
    "Thailand" : "TH",
    "Tunisia" : "TN",
    "Turkey" : "TR",
    "Ukraine" : "UA",
    "United Arab Emirates" : "AE",
    "United Kingdom" : "UK",
    "United States" : "US",
    "Uzbekistan" : "UZ",
    "Venezuela" : "VE",
    "Vietnam" : "VN"
}